<?php
/*
  $Id: conditions.php 1739 2007-12-20 00:52:16Z hpdl $

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2002 osCommerce

  Released under the GNU General Public License
*/

define('NAVBAR_TITLE', 'Terms & Conditions');
define('HEADING_TITLE', 'Terms & Conditions');

define('TEXT_INFORMATION', '<p>
 <p>ORDERS:<br>
All orders are subject to acceptance by SL . We will confirm all orders electronically or via email after receipt of the clients purchase order and deposit (if required). Orders are subject to cancellation by SL if manufacturing or business conditions make it not feasible in the judgment of SL to produce said shipment, or, a credit condition of a customer is deemed to require such action. Further, quotes or invoices are based on issue dates or related issues such as approval of technical drawings by client, possible color sample submission or any other materials that are required to finalize and order. Delivery or lead-times are based on the same as mentioned above and SL reserves the right to delay or increase quoted delivery or lead-times if manufacturing or business conditions make it not feasible in the judgment of SL to deliver said shipment as originally promised.
<p>ORDER PROCESSING:<br>
SL is processing all orders and order tracking online through this catalog and ordering system. Placing an order with SL is easy, just setup your account one time with the correct information. Please be sure your shipping and contact information is up to date. SL does not take any responsibly for incorrect information in your profile reflecting on orders, shipping related documents or invoices, and we do not monitor your information for correctness. All your information will remain on our website until you remove it, as well as your order history. We will update you on your order status through our website or by emails or phone conversations. 
<br>
Retail, stocking-dealer and contract/hospitality orders require a initial minimum opening order of $15,000USD. There is no minimum order required thereafter the initial opening order. <br>
<br>
CUSTOM ORDERS:<br>
Custom orders require a 50% deposit of face value of invoice, and the balance once the order is ready for delivery, but before shipping or releasing the merchandise&nbsp;from the SL warehouse.&nbsp;<br>
Custom orders require clear and professional drawings that need to be approved by the customer with date and signature. If SL quoted a time frame for delivery or production, the official due-date for an order to become active will depend on when drawings where approved with a signature, and/or when the deposit was received. If after placing the order or during production questions arise to clarify product details, we would expect an answer within 24 hours. If it takes longer or even an unreasonable amount of time to get a definite reply or clarification from the customer, we reserve the right to revise the due date on the original invoice as quoted, at our own option and discretion,&nbsp;but within a reasonable time frame. Changes that where made by the customer after the order was placed with signature and deposit received could extend deliver times and pricing as well. Please make sure to receive an revised invoice from our office. </p>
<p>SL is not responsible for delays that could occur due to possible mistakes on drawings, miss leading information or not clearly or logically stated details that could be misinterpreted later on. </p>
<p>PRODUCT AVAILABILITY:<br>
Items in stock are immediately available for shipping. The delivery time on back orders or custom orders can be 8-12 weeks, unless quoted differently in writing. Please confirm with our office before ordering. We cannot guarantee product availability and products, nonetheless, some items may not be available for immediate delivery. We reserve the right, without liability or prior notice, to revise, discontinue, or cease to make available any or all products or to cancel any order.</p>
<p>PAYMENTS:<br>
All prices are F.O.B. Los Angeles from the SL warehouse, or EXW factory Indonesia - whichever one is more feasible. SL accepts checks or wire transfers. Orders are pre-paid only, meaning payments must be received at our office before shipment. <br>
Opening orders for first time buyers; If merchandise is not in stock and has to be back-ordered, we require a 50% deposit, and the balance once merchandise is ready for shipment from our warehouse. Deposits for  orders, or payments made after merchandise was shipped, or was released to the customer, are non-refundable. SL is not responsible for lost checks and bank or wire transfers not received, for any reason. Returned or &quot;insufficient funds&quot; checks might generate additional late fees, and/or cancellation of shipments as well as other active orders a customer might have pending with SL. All prices are subject to change without notice, at any time. </p>
<p>FREIGHT:<br>
SL recommends the use of Blanket Wrap-carriers.  We can arrange shipment of commercial orders via &quot;best way&quot;, unless otherwise indicated on customers purchase order or instructed in writing to our office. SL assumes all shipments to be transferred on a commercial basis, meaning from business to business, as our products are available to the trade only. We do not arrange -home deliveries- or -residential deliveries- or any customer service for this kind of transaction.  If you need merchandise to be delivered to the end-user directly, we assume that you arrange and schedule  a delivery company of your choice, and at  your own risk. All merchandise picked up from our warehouse is inspected by the carrier and accepted with their signature on the invoice as in -First Rate Condition-. Title to merchandise passes to the customer when the carrier accepts delivery from our facilities with their signature. SL is not responsible for any shipping damages, lost goods or any claims that need to be filed with the carrier. <br>
Damaged merchandise (shipping damages) received by the customer must be noted on the carriers Bill of Lading before signing, and claimed directly with the shipping company at the point of delivery. From experience we would like to suggest to support your claim with photos while receiving merchandise from the carrier. Photos taken on the carriers truck or container generally are the best&nbsp;proof to show that merchandise was damaged before you even took possession of the title. Further, SL does not assume any responsability for shipments that might be send by the client to the end-consumer direct from our warehouse facilities. SL expects clients to check and approve merchandise picked up from our warehouse before shipping (or shipping direct) orders to their end-consumer. SL does not reimburse or pay for possible replacement items that need to be shipped if the client did not approve or review items that were shipped to the end-consumer without previous review or approval.</p>
<p>In case of shipping damages or any other issues that might create a claim with a  3rd party, that occurred after the title of merchandise was passed on, customers are still required to make timely payments to SL, as per invoice submitted. Customer may not withhold payments to SL while awaiting settlements of claims from any 3rd parties, or any other companies.</p>
<p>SL does not pre-pay shipping charges nor can we receive payments for shipping related expenses. All shipments are send freight collect or pre-paid, with no exceptions. You are welcome however to make out a check to the shipping company directly and send it to us&nbsp;along with your payment for products. We will then pass on your check to the shipping company upon pickup of your merchandise.</p>
<p>We can assist to generate freight quotes for your order or quote. However, freight quotes provided by a 3rd party shipping company to our office, and passed on to you (the client) are non-binding, nor does SL guaranty its accuracy, validity or any or additional charges or changes in shipping rates that might occur. SL product prices, quotes and estimates are not including  shipping charges&nbsp;or transport of any kind.</p>
<p>WARRANTY:<br>
  SL guarantees its product to be free from defects of workmanship. Our products are hand made from selected natural materials. Due to environmental elements and relative humidity, some of these materials naturally might expand or shrink under certain environmental conditions. Colors on natural materials such as goatskin, shagreen, horn or leathers might fluctuate, due to the natural patterns of these materials.<br>
SL takes great care to carefully construct  furniture at best quality levels and with proper methods, to allow the natural shrinking and expanding. SL does not offer a Money Back Guarantee whatsoever, nor excepts merchandise returns without written authorization from our office, but stands by its product by offering merchandise credits or replacements, at our own option and discretion. </p>
<p>COPYRIGHTED MATERIALS - UNAUTHIRIZED USES REQUIRE PRIOR WRITTEN PERMISSION: <br>
You may not use any Content or Images from the SL website for commercial purposes. You may not sell the Content or sell materials thereof, nor may you use the Content to promote or advertise products or services. You may not use the name SL in conjunction with any products, promotional or commercial purposes, unless you have written permission from SL. If you wish to use&nbsp; Content for any purpose beyond the permitted uses, such as a commercial use or publication (except as may be permitted by fair use under the copyright law), you must obtain prior written permission from the SL office.<br><br>Send your permission request or other inquiries, including requests for higher quality formats, including high resolution digital images to our office. If you are seeking permission to include the Content in a commercial product, or display SL products on your website or any other publication, please acquire written permission from SL by contacting our office at <a href="mailto:info@scalaluxury.com">info@scalaluxury.com</a></p>
<p>TYPOGRAPHICAL ERRORS: <br>
In the event a product is listed at an incorrect price or with incorrect information due to typographical or technical error or error in pricing or product information, we shall have the right to refuse or cancel any orders placed for products listed with incorrect information. We shall have the right to refuse or cancel any such orders whether or not the order has been confirmed.</p>
<p>The terms and conditions of sale herein described shall be enforced in accordance with, and governed by the laws of the State of California. Customer acknowledges and agrees that the courts of the State of California shall have exclusive jurisdiction over any dispute(s). Bidder (in person, by agent, order bid, telephone, internet or by other means) agrees that any dispute arising shall be litigated exclusively in the courts of the State of California. Further, venue shall be in the Superior Court of Los Angeles County, in the state of California.</p>
<p> </p>

</p>
');
?>